function history = importCoeffs(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HISTORY = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  HISTORY = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  history = importfile("C:\Users\39342\Desktop\Universita\Quinto_Anno\Progetto_Aerodinamico\JST2\config\history.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Jun-2023 17:50:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2,Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "CD", "CL", "CMz"];
opts.SelectedVariableNames = ["CD", "CL", "CMz"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "EmptyFieldRule", "auto");

% Import the data
history = readtable(filename, opts);

%% Convert to output type
history = table2array(history);
end